# -*- coding: utf-8 -*-
"""AdjustedScatterPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Adjusted Scatter Plots

# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Load the iris dataset
data = sns.load_dataset("iris")

# Create a scatter plot for sepal length vs. sepal width
sns.scatterplot(
    x="sepal_length",  # X-axis variable
    y="sepal_width",   # Y-axis variable
    data=data,         # Data source
    s=100,             # Marker size
    edgecolor="black", # Marker edge color
    linewidth=1.5      # Edge line width
)

# Display the plot
plt.show()