# -*- coding: utf-8 -*-
"""BarPlotErrors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Bar Plot Errors

import seaborn as sns  # Import seaborn for visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the "tips" dataset
data = sns.load_dataset("tips")

# Create a bar plot with error bars representing standard deviation
sns.barplot(x="day", y="total_bill", data=data, ci="sd")

# Display the plot
plt.show()