# -*- coding: utf-8 -*-
"""BarPlotMeanStd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Bar Plot Mean Std

# Import required libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Load the 'tips' dataset
data = sns.load_dataset("tips")

# Create a bar plot with 'day' on x-axis and 'total_bill' on y-axis, with standard deviation as the error bar
sns.barplot(x="day", y="total_bill", data=data, ci="sd")

# Display the plot
plt.show()