# -*- coding: utf-8 -*-
"""BinnedKDEPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Binned KDE Plots

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("tips")  # Load the "tips" dataset

# Create a histogram of total_bill with different hues for each day
sns.histplot(data, x="total_bill", hue="day", multiple="fill", kde=True)

plt.show()  # Display the plot