# -*- coding: utf-8 -*-
"""BinnedCountPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Binned Count Plots

import seaborn as sns  # Import seaborn library
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("tips")  # Load the 'tips' dataset

sns.histplot(data, x="total_bill", binwidth=5)  # Create histogram of 'total_bill' with binwidth of 5

plt.show()  # Display the plot