# -*- coding: utf-8 -*-
"""BivariateHistogram .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Bivariate Histogram

# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Load the 'tips' dataset from seaborn
data = sns.load_dataset("tips")

# Create a histogram plot for 'total_bill' vs 'tip'
sns.histplot(x="total_bill", y="tip", data=data)

# Display the plot
plt.show()