# -*- coding: utf-8 -*-
"""BoxenPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Boxen Plot

import seaborn as sns  # Import Seaborn for data visualization
import matplotlib.pyplot as plt  # Import Matplotlib for plotting

data = sns.load_dataset("tips")  # Load the 'tips' dataset

# Create a boxen plot with 'day' on the x-axis and 'total_bill' on the y-axis
sns.boxenplot(x="day", y="total_bill", data=data)

plt.show()  # Display the plot