# -*- coding: utf-8 -*-
"""BubblePlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Bubble Plot

import seaborn as sns  # Import seaborn library
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the tips dataset from seaborn
data = sns.load_dataset("tips")

# Create a scatter plot with total_bill on x-axis and tip on y-axis
sns.scatterplot(x="total_bill", y="tip", size="size", hue="size", data=data, sizes=(20, 200))

# Show the plot
plt.show()