# -*- coding: utf-8 -*-
"""BumpChartPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Bump Chart Plot

import seaborn as sns  # For data visualization
import matplotlib.pyplot as plt  # For plotting
import pandas as pd  # For data manipulation

# Create a DataFrame with ranking data
data = pd.DataFrame({
    "Year": ["2010", "2011", "2012", "2013"],  # Years
    "Rank A": [1, 2, 3, 1],  # Rankings for A
    "Rank B": [2, 1, 2, 3]   # Rankings for B
})

# Plot Rank A with a line and markers
sns.lineplot(x="Year", y="Rank A", marker="o", data=data)

# Plot Rank B with a line and markers
sns.lineplot(x="Year", y="Rank B", marker="o", data=data)

# Invert the y-axis to show lower ranks at the top
plt.gca().invert_yaxis()

# Display the plot
plt.show()