# -*- coding: utf-8 -*-
"""ClusterMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Cluster Map

import seaborn as sns  # For data visualization
import matplotlib.pyplot as plt  # For plotting

# Load the Iris dataset and remove the 'species' column
data = sns.load_dataset("iris").drop(columns=["species"])

# Create a clustered heatmap with a coolwarm color map
sns.clustermap(data, cmap="coolwarm")

# Display the plot
plt.show()