# -*- coding: utf-8 -*-
"""ClusteredPairPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Clustered Pair Plot

import seaborn as sns  # For loading the dataset
import matplotlib.pyplot as plt  # For plotting
from scipy.cluster.hierarchy import linkage, dendrogram  # For hierarchical clustering

# Load Iris dataset and remove the 'species' column
data = sns.load_dataset("iris").drop(columns=["species"])

# Perform hierarchical clustering using Ward's method
linkage_matrix = linkage(data, "ward")

# Create a dendrogram and truncate to show top 3 levels
dendrogram(linkage_matrix, truncate_mode="level", p=3)

# Display the plot
plt.show()