# -*- coding: utf-8 -*-
"""ConditionalDensity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uedgQNT0jzpShVcGu2i7QwyIIno8VGe0
"""

# Conditional Density

# Import libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Load the "tips" dataset
data = sns.load_dataset("tips")

# Create a KDE plot of total_bill, grouped by sex, with shaded areas
sns.kdeplot(data=data, x="total_bill", hue="sex", fill=True)

# Display the plot
plt.show()