# -*- coding: utf-8 -*-
"""MultiLevel Violin .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# MultiLevel Violin

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the built-in 'tips' dataset
data = sns.load_dataset("tips")

# Create a violin plot with 'day' on x-axis, 'total_bill' on y-axis, split by 'sex'
sns.violinplot(x="day", y="total_bill", hue="sex", split=True, data=data)

# Display the plot
plt.show()

