# -*- coding: utf-8 -*-
"""MultipleHeatMapPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Multiple HeatMap Plot

import seaborn as sns  # Import seaborn for heatmap
import matplotlib.pyplot as plt  # Import matplotlib for plotting
import numpy as np  # Import numpy for generating random data

# Generate two 10x10 random datasets
data1 = np.random.rand(10, 10)
data2 = np.random.rand(10, 10)

# Create subplots (1 row, 2 columns)
fig, axs = plt.subplots(1, 2, figsize=(10, 5))

# Plot heatmap for the first dataset
sns.heatmap(data1, ax=axs[0], cmap="YlGnBu")

# Plot heatmap for the second dataset
sns.heatmap(data2, ax=axs[1], cmap="coolwarm")

# Display the plots
plt.show()

