# -*- coding: utf-8 -*-
"""OrderedViolinPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Ordered Violin Plot

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the tips dataset
data = sns.load_dataset("tips")

# Create a violin plot with 'day' on x-axis and 'total_bill' on y-axis
sns.violinplot(x="day", y="total_bill", data=data, order=["Thur", "Fri", "Sat", "Sun"])

# Display the plot
plt.show()

