# -*- coding: utf-8 -*-
"""PairGrid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Pair Grid

import seaborn as sns; import matplotlib.pyplot as plt

# Load 'tips' dataset
data = sns.load_dataset("tips")

# Create a PairGrid with 'sex' as hue for color differentiation
g = sns.PairGrid(data, hue="sex")

# Map histograms on the diagonal
g.map_diag(sns.histplot)

# Map scatter plots on off-diagonal
g.map_offdiag(sns.scatterplot)

# Add legend for hue
g.add_legend()

# Display the plot
plt.show()

