# -*- coding: utf-8 -*-
"""PieChart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Pie Chart

import matplotlib.pyplot as plt  # Import plotting library

sizes = [15, 30, 45, 10]  # Data for the pie chart
labels = ['A', 'B', 'C', 'D']  # Labels for the sections

# Create pie chart with percentage display
plt.pie(sizes, labels=labels, autopct='%1.1f%%')

# Add title to the chart
plt.title("Pie Chart Example")

# Display the chart
plt.show()

