# -*- coding: utf-8 -*-
"""PolarKDE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Polar KDE

import seaborn as sns  # Import seaborn for dataset
import matplotlib.pyplot as plt  # Import matplotlib for plotting
import numpy as np  # Import numpy for numerical operations

data = sns.load_dataset("iris")  # Load iris dataset
theta = np.linspace(0, 2*np.pi, len(data["sepal_length"]))  # Generate angular values
r = data["sepal_length"]  # Extract sepal_length as radial values

plt.polar(theta, r, marker="o", linestyle="None")  # Plot data on polar plot
plt.show()  # Display the plot

