# -*- coding: utf-8 -*-
"""PopulationPyramid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Population Pyramid
import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("titanic")  # Load the Titanic dataset

# Create a histogram for 'age', grouped by 'sex', with separate bars
sns.histplot(data, y="age", hue="sex", multiple="dodge", shrink=0.8)

plt.show()  # Display the plot

