# -*- coding: utf-8 -*-
"""QuantilePlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Quantile Plot

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("tips")  # Load the "tips" dataset

# Plot ECDF (Empirical Cumulative Distribution Function) of total_bill as proportions
sns.ecdfplot(data["total_bill"], stat="proportion")

plt.show()  # Display the plot

