# -*- coding: utf-8 -*-
"""RadarPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Radar Plot

import numpy as np
import matplotlib.pyplot as plt

# Define labels and values
labels = np.array(['A', 'B', 'C', 'D', 'E'])
values = np.array([4, 3, 2, 5, 4])

# Calculate angles for each label
angles = np.linspace(0, 2 * np.pi, len(labels), endpoint=False).tolist()

# Close the loop by adding the first value again
values = np.concatenate((values, [values[0]]))
angles = np.concatenate((angles, [angles[0]]))

# Create polar plot
fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))

# Fill the area and plot the values
ax.fill(angles, values, color='blue', alpha=0.25)
ax.plot(angles, values, color='blue', linewidth=2)

# Remove y-axis labels
ax.set_yticklabels([])

# Set labels for the x-axis
ax.set_xticks(angles[:-1])
ax.set_xticklabels(labels)

# Display the plot
plt.show()

