# -*- coding: utf-8 -*-
"""RaincloudPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Raincloud Plot

import seaborn as sns  # Import seaborn library
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the 'tips' dataset
data = sns.load_dataset("tips")

# Create a violin plot with splitting based on sex
sns.violinplot(x="day", y="total_bill", hue="sex", split=True, data=data)

# Add a strip plot with dodging for different sexes and set transparency
sns.stripplot(x="day", y="total_bill", hue="sex", data=data, dodge=True, color="gray", alpha=0.5)

# Display the plot
plt.show()

