# -*- coding: utf-8 -*-
"""RugPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Rug Plot

# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Load the built-in "tips" dataset
data = sns.load_dataset("tips")

# Create a rug plot for the "total_bill" column
sns.rugplot(data["total_bill"])

# Display the plot
plt.show()

