# -*- coding: utf-8 -*-
"""ScatterRegressionCategory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Scatter Regression Category

import seaborn as sns  # Import seaborn for visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the 'tips' dataset
data = sns.load_dataset("tips")

# Create a scatter plot with a regression line, colored by sex
sns.lmplot(x="total_bill", y="tip", hue="sex", data=data)

# Display the plot
plt.show()

