# -*- coding: utf-8 -*-
"""ScatterDensityEstimation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Scatter Density Estimation

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("iris")  # Load the iris dataset

# Create a KDE plot of sepal_length vs sepal_width with filled contour
sns.kdeplot(x=data["sepal_length"], y=data["sepal_width"], cmap="Blues", fill=True)

# Overlay scatter plot of sepal_length and sepal_width with orange points
plt.scatter(data["sepal_length"], data["sepal_width"], color="orange", s=5)

plt.show()  # Display the plot

