# -*- coding: utf-8 -*-
"""ScatterTrendLines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Scatter trend lines

import seaborn as sns  # Import seaborn library
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("tips")  # Load the 'tips' dataset from seaborn

sns.lmplot(x="total_bill", y="tip", hue="sex", data=data)  # Create a scatter plot with regression line, colored by 'sex'

plt.show()  # Display the plot

