# -*- coding: utf-8 -*-
"""ScatterErrorsBar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Scatter Errors Bar

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the 'tips' dataset
data = sns.load_dataset("tips")

# Create a scatter plot of total bill vs tip
sns.scatterplot(x="total_bill", y="tip", data=data)

# Add error bars on the y-axis with a fixed error of 0.2
plt.errorbar(data["total_bill"], data["tip"], yerr=0.2, fmt="o", color="gray", alpha=0.5)

# Display the plot
plt.show()

