# -*- coding: utf-8 -*-
"""Scatter3DPlot .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Scatter 3D Plot

import matplotlib.pyplot as plt  # Import for plotting
from mpl_toolkits.mplot3d import Axes3D  # 3D plotting support
import seaborn as sns; import numpy as np  # Seaborn for dataset, NumPy for numerical operations

# Load the Iris dataset
data = sns.load_dataset("iris")

# Create a 3D plot
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

# Scatter plot with sepal_length, sepal_width, and petal_length
ax.scatter(data["sepal_length"], data["sepal_width"], data["petal_length"], c="blue", marker="o")

# Display the plot
plt.show()

