# -*- coding: utf-8 -*-
"""ScatterBubble .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Scatter Bubble

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the built-in 'tips' dataset
data = sns.load_dataset("tips")

# Create a scatter plot with 'total_bill' vs 'tip', using 'size' for point size and 'day' for color
sns.scatterplot(x="total_bill", y="tip", size="size", hue="day", data=data, sizes=(20, 200))

# Display the plot
plt.show()

