# -*- coding: utf-8 -*-
"""SeabornVisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Seaborn Visualization

import seaborn as sns
import matplotlib.pyplot as plt

# Load sample dataset
data = sns.load_dataset("tips")

# 1. Scatter Plot: Total Bill vs Tip
plt.figure(figsize=(8, 6))
sns.scatterplot(x="total_bill", y="tip", data=data)
plt.title("Scatter Plot of Total Bill vs Tip")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

# 2. Line Plot: Size vs Total Bill
plt.figure(figsize=(8, 6))
sns.lineplot(x="size", y="total_bill", data=data)
plt.title("Line Plot of Size vs Total Bill")
plt.xlabel("Size")
plt.ylabel("Total Bill")
plt.show()

# 3. Histogram: Total Bill with KDE
plt.figure(figsize=(8, 6))
sns.histplot(data["total_bill"], kde=True)
plt.title("Histogram of Total Bill with KDE")
plt.xlabel("Total Bill")
plt.show()

# 4. Bar Plot: Total Bill by Day (Sum)
plt.figure(figsize=(8, 6))
sns.barplot(x="day", y="total_bill", data=data, estimator=sum)
plt.title("Total Bill by Day")
plt.xlabel("Day")
plt.ylabel("Total Bill (Sum)")
plt.show()

# 5. Box Plot: Total Bill by Day
plt.figure(figsize=(8, 6))
sns.boxplot(x="day", y="total_bill", data=data)
plt.title("Box Plot of Total Bill by Day")
plt.xlabel("Day")
plt.ylabel("Total Bill")
plt.show()

# 6. Violin Plot: Total Bill by Day
plt.figure(figsize=(8, 6))
sns.violinplot(x="day", y="total_bill", data=data)
plt.title("Violin Plot of Total Bill by Day")
plt.xlabel("Day")
plt.ylabel("Total Bill")
plt.show()

# 7. Pair Plot: Total Bill, Tip, and Size
sns.pairplot(data[["total_bill", "tip", "size"]])
plt.suptitle("Pair Plot of Total Bill, Tip, and Size", y=1.02)
plt.show()

# 8. Heatmap: Correlation Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(data.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# 9. Count Plot: Count of Days
plt.figure(figsize=(8, 6))
sns.countplot(x="day", data=data)
plt.title("Count of Days")
plt.xlabel("Day")
plt.show()

# 10. Strip Plot: Total Bill by Day
plt.figure(figsize=(8, 6))
sns.stripplot(x="day", y="total_bill", data=data)
plt.title("Strip Plot of Total Bill by Day")
plt.xlabel("Day")
plt.ylabel("Total Bill")
plt.show()

