# -*- coding: utf-8 -*-
"""SeasonalPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Seasonal Plots

# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Load the 'flights' dataset from seaborn
data = sns.load_dataset("flights")

# Create a lineplot with months on the x-axis, passengers on the y-axis, and year as the hue
sns.lineplot(x="month", y="passengers", hue="year", data=data)

# Display the plot
plt.show()

