# -*- coding: utf-8 -*-
"""SeasonalitySubPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Seasonality Sub Plots

import seaborn as sns  # Import Seaborn library
import matplotlib.pyplot as plt  # Import Matplotlib for plotting

# Load the built-in "flights" dataset
data = sns.load_dataset("flights")

# Create a FacetGrid with columns for each month, wrapping at 4 columns
g = sns.FacetGrid(data, col="month", col_wrap=4, height=2.5)

# Map line plot to each facet, using year as x-axis and passengers as y-axis
g.map(sns.lineplot, "year", "passengers")

# Display the plot
plt.show()

