# -*- coding: utf-8 -*-
"""SideKDEPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Side KDE Plots

import seaborn as sns  # Import seaborn for plotting
import matplotlib.pyplot as plt  # Import matplotlib for showing the plot

data = sns.load_dataset("iris")  # Load the iris dataset

sns.kdeplot(data=data, x="sepal_length", hue="species", fill=True)  # Plot KDE with sepal_length, differentiated by species

plt.show()  # Display the plot

