# -*- coding: utf-8 -*-
"""SmallMultipleLinePlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Small Multiple Line Plots

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the flights dataset
data = sns.load_dataset("flights")

# Create a FacetGrid to plot data by month
g = sns.FacetGrid(data, col="month", col_wrap=4, height=2.5)

# Map lineplot to the grid, plotting 'year' vs 'passengers'
g.map(sns.lineplot, "year", "passengers")

# Show the plot
plt.show()

