# -*- coding: utf-8 -*-
"""SmallMultipleDotPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Small Multiple Dot Plots

import seaborn as sns  # Import seaborn for visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the 'tips' dataset from seaborn
data = sns.load_dataset("tips")

# Create a FacetGrid for separate plots based on 'day'
g = sns.FacetGrid(data, col="day")

# Map stripplot on each facet, comparing 'time' vs 'total_bill'
g.map(sns.stripplot, "time", "total_bill")

# Display the plot
plt.show()

