# -*- coding: utf-8 -*-
"""SplitDensityPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Split Density Plots

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the built-in 'tips' dataset
data = sns.load_dataset("tips")

# Create a KDE plot of 'total_bill' based on 'time' (lunch/dinner)
sns.kdeplot(x="total_bill", hue="time", data=data, fill=True)

# Show the plot
plt.show()

