# -*- coding: utf-8 -*-
"""SplitBoxenPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Split Boxen Plots

import seaborn as sns  # Import seaborn for visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("tips")  # Load the 'tips' dataset

# Create a boxen plot to show total_bill distribution by day, split by sex
sns.boxenplot(x="day", y="total_bill", hue="sex", data=data)

plt.show()  # Display the plot

