# -*- coding: utf-8 -*-
"""SplitViolinPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Split Violin Plots

import seaborn as sns  # Import seaborn library
import matplotlib.pyplot as plt  # Import matplotlib for plotting

data = sns.load_dataset("tips")  # Load the 'tips' dataset

# Create a violin plot to show the distribution of total_bill by day, split by sex
sns.violinplot(x="day", y="total_bill", hue="sex", data=data, split=True)

plt.show()  # Display the plot

