# -*- coding: utf-8 -*-
"""StackedHistogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# stacked histogram

import seaborn as sns  # Import seaborn for data visualization
import matplotlib.pyplot as plt  # Import matplotlib for plotting

# Load the "tips" dataset
data = sns.load_dataset("tips")

# Create a stacked histogram for "total_bill" with hue based on "sex"
sns.histplot(data=data, x="total_bill", hue="sex", multiple="stack")

# Display the plot
plt.show()

