# -*- coding: utf-8 -*-
"""StackedBarCategory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Stacked Bar Category

# Importing necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Loading Titanic dataset
data = sns.load_dataset("titanic")

# Plotting stacked histogram with 'class' on x-axis and 'sex' as hue
sns.histplot(data=data, x="class", hue="sex", multiple="stack")

# Displaying the plot
plt.show()

