# -*- coding: utf-8 -*-
"""StackedAreaPlots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Stacked Area Plots

import matplotlib.pyplot as plt  # Import plotting library
import numpy as np  # Import NumPy for random number generation

x = np.arange(1, 11)  # Create an array for x-axis values (1 to 10)
y1 = np.random.randint(1, 10, size=10)  # Generate random values for y1
y2 = np.random.randint(1, 10, size=10)  # Generate random values for y2
y3 = np.random.randint(1, 10, size=10)  # Generate random values for y3

# Create a stacked area plot with 3 datasets (y1, y2, y3)
plt.stackplot(x, y1, y2, y3, labels=["A", "B", "C"], alpha=0.6)

# Add a legend in the upper left corner
plt.legend(loc="upper left")

# Display the plot
plt.show()

