# -*- coding: utf-8 -*-
"""SwarmPolt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

#Swarm Polt
# Import necessary libraries
import seaborn as sns  # For creating beautiful statistical visualizations
import matplotlib.pyplot as plt  # For displaying the plot

# Load the "tips" dataset from seaborn's built-in datasets
data = sns.load_dataset("tips")

# Create a swarm plot to show the distribution of total bills for each day
# x: Categorical variable representing the days of the week
# y: Numerical variable representing the total bill amounts
# data: The dataset containing the variables
sns.swarmplot(x="day", y="total_bill", data=data)

# Display the plot
plt.show()

