# -*- coding: utf-8 -*-
"""SwarmBoxOverlay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

#Swarm Box Overlay
# Import necessary libraries
import seaborn as sns  # Seaborn for creating advanced plots
import matplotlib.pyplot as plt  # Matplotlib for plot customization and display

# Load the "tips" dataset provided by seaborn
data = sns.load_dataset("tips")

# Create a boxplot to visualize the distribution of total_bill across days
# The boxplot shows median, quartiles, and potential outliers
sns.boxplot(
    x="day",  # Categorical variable on the x-axis (days of the week)
    y="total_bill",  # Numerical variable on the y-axis (total bill amount)
    data=data,  # Dataset containing the variables
    color="white"  # Set boxplot color to white
)

# Overlay a swarmplot on the boxplot
# Swarmplot shows individual data points, providing a sense of density and spread
sns.swarmplot(
    x="day",  # Same x-axis variable (days of the week)
    y="total_bill",  # Same y-axis variable (total bill amount)
    data=data,  # Dataset containing the variables
    color=".25"  # Set swarmplot color to a light gray shade
)

# Display the plot
plt.show()

