# -*- coding: utf-8 -*-
"""SymmetricHeatmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

#Symmetric Heatmap

# Import necessary libraries
import seaborn as sns  # For data visualization and working with datasets
import matplotlib.pyplot as plt  # For plotting the heatmap

# Load the "iris" dataset provided by seaborn
iris_data = sns.load_dataset("iris")

# Calculate the correlation matrix for numerical columns
# Exclude the last column ('species') which is non-numeric
correlation_matrix = iris_data.iloc[:, :-1].corr()

# Create a heatmap to visualize the correlation matrix
# 'cmap="coolwarm"' sets the color scheme
# 'center=0' ensures the color gradient is centered around 0
# 'annot=True' displays the correlation coefficients on the heatmap
sns.heatmap(correlation_matrix, cmap="coolwarm", center=0, annot=True)

# Display the heatmap
plt.show()

