# -*- coding: utf-8 -*-
"""TimeSeriesHeatmapPolts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

# Time series heatmap plots
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
data = sns.load_dataset("flights")

# Pivot the data properly
pivoted_data = data.pivot(index="month", columns="year", values="passengers")

# Create a heatmap
sns.heatmap(pivoted_data, cmap="YlGnBu")
plt.show()

