# -*- coding: utf-8 -*-
"""ViolinplotInnerQuartile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPHJxHB4EVtIGGMNSSw-Pcs5eZ8LftPX
"""

import seaborn as sns; import matplotlib.pyplot as plt
data = sns.load_dataset("tips")
sns.violinplot(x="day", y="total_bill", data=data, inner="quartile") #violinplot inner quartile
plt.show()

